before_install:
- gem install cocoapods -v '0.33.1'
- brew update
- brew upgrade xctool

env:
  global:
    - HS_CLIENT_ID='@"234234342asfda"' HS_CLIENT_SECRET='@"23423hjkh234123kjhkjh"' TESTFLIGHT_APP_ID='@"sdfa89fd-df89-2343-fd89-23432353234h"'

language: objective-c
script:
- xctool -workspace SecretHandshake.xcworkspace -scheme SecretHandshake -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO clean build test
