before_install:
  - gem install cocoapods -v '0.33.1'
  - brew update
  - brew upgrade xctool
  
language: objective-c
script:
  - xctool -workspace SecretHandshake.xcworkspace -scheme SecretHandshake -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test