before_install:
- gem install cocoapods -v '0.33.1'
- brew update
- brew install xctool
- cp Configuration.example.plist Configuration.plist

language: objective-c
script:
- xctool -workspace SecretHandshake.xcworkspace -scheme SecretHandshake -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
